// Generated by backend/scripts/generate_contracts.py. Do not edit by hand.
export const CONTRACT_VERSION = "1.0" as const;
export const REVIEW_CAPABILITIES = ["review.download.finalized_original", "review.finalization.create", "review.finalization.read", "review.issue.create", "review.issue.delete", "review.issue.read", "review.issue.reopen", "review.issue.reply", "review.issue.resolve", "review.issue.update", "review.item.create", "review.item.delete", "review.item.read", "review.item.update", "review.package.create", "review.package.download", "review.package.read", "review.project.archive", "review.project.create", "review.project.delete", "review.project.read", "review.project.restore", "review.project.update", "review.session.request_changes", "review.session.start", "review.version.compare", "review.version.read", "review.version.upload"] as const;
export type ReviewCapability = "review.download.finalized_original" | "review.finalization.create" | "review.finalization.read" | "review.issue.create" | "review.issue.delete" | "review.issue.read" | "review.issue.reopen" | "review.issue.reply" | "review.issue.resolve" | "review.issue.update" | "review.item.create" | "review.item.delete" | "review.item.read" | "review.item.update" | "review.package.create" | "review.package.download" | "review.package.read" | "review.project.archive" | "review.project.create" | "review.project.delete" | "review.project.read" | "review.project.restore" | "review.project.update" | "review.session.request_changes" | "review.session.start" | "review.version.compare" | "review.version.read" | "review.version.upload";
export const EDIT_ENTRY_PROFILE = ["review.project.read", "review.project.create", "review.project.update", "review.item.read", "review.item.create", "review.item.update", "review.item.delete", "review.version.read", "review.version.upload", "review.version.compare", "review.issue.read", "review.finalization.read", "review.download.finalized_original"] as const;
export const REVIEW_ENTRY_PROFILE = ["review.project.read", "review.project.archive", "review.project.restore", "review.project.delete", "review.item.read", "review.version.read", "review.version.compare", "review.issue.read", "review.issue.create", "review.issue.update", "review.issue.reply", "review.issue.resolve", "review.issue.reopen", "review.issue.delete", "review.session.start", "review.session.request_changes", "review.finalization.read", "review.finalization.create", "review.download.finalized_original", "review.package.create", "review.package.read", "review.package.download"] as const;
export type CommandType = "FinalizeVersion" | "StartReview" | "CreateReviewIssue" | "UpdateReviewIssue" | "AddReviewMessage" | "ResolveReviewIssue" | "ReopenReviewIssue" | "SoftDeleteReviewIssue" | "RequestChanges" | "PrepareFinalizedPackage" | "CreateProject" | "UpdateProject" | "ArchiveProject" | "RestoreProject" | "SoftDeleteProject" | "CreateReviewItem" | "UpdateReviewItem" | "DeleteReviewItem" | "UploadReviewVersion";
export const IDEMPOTENT_COMMANDS = ["AddReviewMessage", "CreateProject", "CreateReviewIssue", "CreateReviewItem", "FinalizeVersion", "PrepareFinalizedPackage", "RequestChanges", "UploadReviewVersion"] as const;
export type DomainEventType = "review.project.created" | "review.project.updated" | "review.project.archived" | "review.project.restored" | "review.project.deleted" | "review.item.created" | "review.item.updated" | "review.item.deleted" | "review.version.uploaded" | "review.session.started" | "review.issue.created" | "review.issue.updated" | "review.issue.message_added" | "review.issue.resolved" | "review.issue.reopened" | "review.issue.deleted" | "review.changes_requested" | "review.version.finalized" | "review.finalized_original.download_requested" | "review.package.requested" | "review.package.ready" | "review.package.failed";
export const DOMAIN_EVENT_TYPES = ["review.project.created", "review.project.updated", "review.project.archived", "review.project.restored", "review.project.deleted", "review.item.created", "review.item.updated", "review.item.deleted", "review.version.uploaded", "review.session.started", "review.issue.created", "review.issue.updated", "review.issue.message_added", "review.issue.resolved", "review.issue.reopened", "review.issue.deleted", "review.changes_requested", "review.version.finalized", "review.finalized_original.download_requested", "review.package.requested", "review.package.ready", "review.package.failed"] as const;
export const DOMAIN_EVENT_PAYLOAD_SCHEMAS = {
  "review.project.created": {
    "type": "object",
    "additionalProperties": false,
    "required": [
      "project_code"
    ],
    "properties": {
      "project_code": {
        "type": "string",
        "minLength": 1
      }
    }
  },
  "review.project.updated": {
    "type": "object",
    "additionalProperties": false,
    "properties": {}
  },
  "review.project.archived": {
    "type": "object",
    "additionalProperties": false,
    "properties": {}
  },
  "review.project.restored": {
    "type": "object",
    "additionalProperties": false,
    "properties": {}
  },
  "review.project.deleted": {
    "type": "object",
    "additionalProperties": false,
    "properties": {}
  },
  "review.item.created": {
    "type": "object",
    "additionalProperties": false,
    "properties": {}
  },
  "review.item.updated": {
    "type": "object",
    "additionalProperties": false,
    "properties": {}
  },
  "review.item.deleted": {
    "type": "object",
    "additionalProperties": false,
    "properties": {}
  },
  "review.version.uploaded": {
    "type": "object",
    "additionalProperties": false,
    "properties": {}
  },
  "review.session.started": {
    "type": "object",
    "additionalProperties": false,
    "properties": {}
  },
  "review.issue.created": {
    "type": "object",
    "additionalProperties": false,
    "properties": {}
  },
  "review.issue.updated": {
    "type": "object",
    "additionalProperties": false,
    "properties": {}
  },
  "review.issue.message_added": {
    "type": "object",
    "additionalProperties": false,
    "properties": {}
  },
  "review.issue.resolved": {
    "type": "object",
    "additionalProperties": false,
    "properties": {}
  },
  "review.issue.reopened": {
    "type": "object",
    "additionalProperties": false,
    "properties": {}
  },
  "review.issue.deleted": {
    "type": "object",
    "additionalProperties": false,
    "properties": {}
  },
  "review.changes_requested": {
    "type": "object",
    "additionalProperties": false,
    "properties": {}
  },
  "review.version.finalized": {
    "type": "object",
    "additionalProperties": false,
    "properties": {}
  },
  "review.finalized_original.download_requested": {
    "type": "object",
    "additionalProperties": false,
    "properties": {}
  },
  "review.package.requested": {
    "type": "object",
    "additionalProperties": false,
    "properties": {}
  },
  "review.package.ready": {
    "type": "object",
    "additionalProperties": false,
    "properties": {}
  },
  "review.package.failed": {
    "type": "object",
    "additionalProperties": false,
    "required": [
      "error_code"
    ],
    "properties": {
      "error_code": {
        "type": "string",
        "minLength": 1
      }
    }
  }
} as const;
export const ERROR_HTTP_STATUS = {
  "VALIDATION_ERROR": 422,
  "RESOURCE_NOT_FOUND": 404,
  "METHOD_NOT_ALLOWED": 405,
  "ENTRY_CAPABILITY_DENIED": 403,
  "PRINCIPAL_AUTHENTICATION_REQUIRED": 401,
  "PRINCIPAL_PERMISSION_DENIED": 403,
  "WRITE_GUARD_REQUIRED": 403,
  "WRITE_GUARD_INVALID": 403,
  "RESOURCE_STATE_CONFLICT": 409,
  "PORT_OPERATION_NOT_SUPPORTED": 409,
  "PLAYBACK_NOT_READY": 409,
  "VERSION_NOT_CURRENT": 409,
  "REVIEW_IN_PROGRESS": 409,
  "REVIEW_ITEM_FINALIZED": 409,
  "UNRESOLVED_ISSUES_EXIST": 409,
  "NO_UNRESOLVED_ISSUE": 409,
  "VERSION_FILE_NOT_READY": 409,
  "FILE_HASH_MISMATCH": 409,
  "UPLOAD_INCOMPLETE": 409,
  "IDEMPOTENCY_CONFLICT": 409,
  "OPTIMISTIC_LOCK_CONFLICT": 409,
  "PACKAGE_NO_FINALIZED_FILES": 409,
  "PACKAGE_SOURCE_MISSING": 409,
  "PACKAGE_NOT_READY": 409,
  "PACKAGE_EXPIRED": 410,
  "FILE_TYPE_NOT_ALLOWED": 422,
  "FILE_TOO_LARGE": 413,
  "STORAGE_UNAVAILABLE": 503,
  "INTERNAL_SERVER_ERROR": 500
} as const;
export type ErrorCode = keyof typeof ERROR_HTTP_STATUS;
export type ErrorHttpStatus = 401 | 403 | 404 | 405 | 409 | 410 | 413 | 422 | 500 | 503;
export const COMMAND_CAPABILITIES = {
  "FinalizeVersion": "review.finalization.create",
  "StartReview": "review.session.start",
  "CreateReviewIssue": "review.issue.create",
  "UpdateReviewIssue": "review.issue.update",
  "AddReviewMessage": "review.issue.reply",
  "ResolveReviewIssue": "review.issue.resolve",
  "ReopenReviewIssue": "review.issue.reopen",
  "SoftDeleteReviewIssue": "review.issue.delete",
  "RequestChanges": "review.session.request_changes",
  "PrepareFinalizedPackage": "review.package.create",
  "CreateProject": "review.project.create",
  "UpdateProject": "review.project.update",
  "ArchiveProject": "review.project.archive",
  "RestoreProject": "review.project.restore",
  "SoftDeleteProject": "review.project.delete",
  "CreateReviewItem": "review.item.create",
  "UpdateReviewItem": "review.item.update",
  "DeleteReviewItem": "review.item.delete",
  "UploadReviewVersion": "review.version.upload"
} as const;
export const MODULE_MANIFEST = {
  "manifest_version": 1,
  "module_id": "final-cut-review",
  "module_version": "1.3.0",
  "contract_version": "1.0",
  "standalone_routes": {
    "edit": "/edit",
    "review": "/review"
  },
  "mount_slots": [
    "workspace.main"
  ],
  "capabilities": [
    "review.project.read",
    "review.project.create",
    "review.project.update",
    "review.project.archive",
    "review.project.restore",
    "review.project.delete",
    "review.item.read",
    "review.item.create",
    "review.item.update",
    "review.item.delete",
    "review.version.read",
    "review.version.upload",
    "review.version.compare",
    "review.issue.read",
    "review.issue.create",
    "review.issue.update",
    "review.issue.reply",
    "review.issue.resolve",
    "review.issue.reopen",
    "review.issue.delete",
    "review.session.start",
    "review.session.request_changes",
    "review.finalization.read",
    "review.finalization.create",
    "review.download.finalized_original",
    "review.package.create",
    "review.package.read",
    "review.package.download"
  ],
  "required_host_services": [],
  "optional_host_services": [
    "project_catalog",
    "principal_context",
    "authorization"
  ]
} as const;
