// Generated by backend/scripts/generate_contracts.py. Do not edit by hand.
import type { DomainEventType } from "./backend-contract-metadata";

export interface FinalizeVersionPayload {
  project_ref_id: string;
  review_item_id: string;
  version_id: string;
  confirmed: true;
}

export interface StartReviewPayload {
  project_ref_id: string;
  review_item_id: string;
}

export interface CreateReviewIssuePayload {
  project_ref_id: string;
  review_item_id: string;
  version_id: string;
  content: string;
  timestamp_ms: number;
  frame_number: number;
  annotation?: { "canvas_width": number; "canvas_height": number; "video_width": number; "video_height": number; "shapes": { "id": string; "tool_type": "pen" | "arrow" | "rect" | "circle" | "text"; "anchor_points"?: { "x": number; "y": number }[]; "path_data"?: string; "text_content"?: string; "color": string; "line_width": number; "font_size"?: number; "z_index": number }[] };
}

export interface UpdateReviewIssuePayload {
  project_ref_id: string;
  review_item_id: string;
  version_id: string;
  issue_id: string;
  content?: string;
  annotation?: { "canvas_width": number; "canvas_height": number; "video_width": number; "video_height": number; "shapes": { "id": string; "tool_type": "pen" | "arrow" | "rect" | "circle" | "text"; "anchor_points"?: { "x": number; "y": number }[]; "path_data"?: string; "text_content"?: string; "color": string; "line_width": number; "font_size"?: number; "z_index": number }[] };
}

export interface AddReviewMessagePayload {
  project_ref_id: string;
  review_item_id: string;
  version_id: string;
  issue_id: string;
  content: string;
}

export interface ResolveReviewIssuePayload {
  project_ref_id: string;
  review_item_id: string;
  version_id: string;
  issue_id: string;
}

export interface ReopenReviewIssuePayload {
  project_ref_id: string;
  review_item_id: string;
  version_id: string;
  issue_id: string;
}

export interface SoftDeleteReviewIssuePayload {
  project_ref_id: string;
  review_item_id: string;
  version_id: string;
  issue_id: string;
}

export interface RequestChangesPayload {
  project_ref_id: string;
  review_item_id: string;
  version_id: string;
  summary: string;
}

export interface PrepareFinalizedPackagePayload {
  project_ref_id: string;
}

export interface CreateProjectPayload {
  project_code: string;
  project_name: string;
  description?: string;
  external_project_id?: string;
}

export interface UpdateProjectPayload {
  project_ref_id: string;
  project_name: string;
  description: string;
}

export interface ArchiveProjectPayload {
  project_ref_id: string;
}

export interface RestoreProjectPayload {
  project_ref_id: string;
}

export interface SoftDeleteProjectPayload {
  project_ref_id: string;
  confirmed: true;
}

export interface CreateReviewItemPayload {
  project_ref_id: string;
  item_code: string;
  episode_no?: number;
  title: string;
  original_file_id: string;
  version_note?: string;
}

export interface UpdateReviewItemPayload {
  project_ref_id: string;
  review_item_id: string;
  episode_no?: number;
  title?: string;
}

export interface DeleteReviewItemPayload {
  project_ref_id: string;
  review_item_id: string;
  confirmed: true;
}

export interface UploadReviewVersionPayload {
  project_ref_id: string;
  review_item_id: string;
  original_file_id: string;
  version_note?: string;
  change_summary?: string;
  supersede_reason?: string;
}

export type EmptyPayload = Record<string, never>;

export interface ReviewProjectCreatedPayload {
  project_code: string;
}

export type ReviewProjectUpdatedPayload = Record<string, never>;

export type ReviewProjectArchivedPayload = Record<string, never>;

export type ReviewProjectRestoredPayload = Record<string, never>;

export type ReviewProjectDeletedPayload = Record<string, never>;

export type ReviewItemCreatedPayload = Record<string, never>;

export type ReviewItemUpdatedPayload = Record<string, never>;

export type ReviewItemDeletedPayload = Record<string, never>;

export type ReviewVersionUploadedPayload = Record<string, never>;

export type ReviewSessionStartedPayload = Record<string, never>;

export type ReviewIssueCreatedPayload = Record<string, never>;

export type ReviewIssueUpdatedPayload = Record<string, never>;

export type ReviewIssueMessageAddedPayload = Record<string, never>;

export type ReviewIssueResolvedPayload = Record<string, never>;

export type ReviewIssueReopenedPayload = Record<string, never>;

export type ReviewIssueDeletedPayload = Record<string, never>;

export type ReviewChangesRequestedPayload = Record<string, never>;

export type ReviewVersionFinalizedPayload = Record<string, never>;

export type ReviewFinalizedOriginalDownloadRequestedPayload = Record<string, never>;

export type ReviewPackageRequestedPayload = Record<string, never>;

export type ReviewPackageReadyPayload = Record<string, never>;

export interface ReviewPackageFailedPayload {
  error_code: string;
}

export type DomainEventPayload = ReviewProjectCreatedPayload | ReviewProjectUpdatedPayload | ReviewProjectArchivedPayload | ReviewProjectRestoredPayload | ReviewProjectDeletedPayload | ReviewItemCreatedPayload | ReviewItemUpdatedPayload | ReviewItemDeletedPayload | ReviewVersionUploadedPayload | ReviewSessionStartedPayload | ReviewIssueCreatedPayload | ReviewIssueUpdatedPayload | ReviewIssueMessageAddedPayload | ReviewIssueResolvedPayload | ReviewIssueReopenedPayload | ReviewIssueDeletedPayload | ReviewChangesRequestedPayload | ReviewVersionFinalizedPayload | ReviewFinalizedOriginalDownloadRequestedPayload | ReviewPackageRequestedPayload | ReviewPackageReadyPayload | ReviewPackageFailedPayload;

export interface DomainEventEnvelope {
  event_id: string;
  event_type: DomainEventType;
  event_version: number;
  occurred_at: string;
  aggregate_type: string;
  aggregate_id: string;
  aggregate_version: number;
  sequence: number;
  project_ref_id: string;
  review_item_id?: string | null;
  version_id?: string | null;
  issue_id?: string | null;
  finalization_id?: string | null;
  package_id?: string | null;
  correlation_id: string;
  causation_id?: string | null;
  metadata: Record<string, unknown>;
  payload: DomainEventPayload;
}
