// Generated by backend/scripts/generate_contracts.py. Do not edit by hand.
import type { ErrorCode } from "./backend-contract-metadata";
import type { CommandEnvelope, Envelope, ErrorBody, ErrorEnvelope, ProjectDTO } from "./backend-contract-models";

export class FinalCutReviewHttpError extends Error {
  readonly code: ErrorCode;
  readonly httpStatus: number;
  readonly details: Record<string, unknown>;
  readonly requestId: string;
  readonly timestamp: string;
  readonly contractVersion: string;

  constructor(error: ErrorBody, fallbackStatus: number) {
    super(error.message);
    this.name = "FinalCutReviewHttpError";
    this.code = error.code;
    this.httpStatus = error.http_status ?? fallbackStatus;
    this.details = error.details;
    this.requestId = error.request_id;
    this.timestamp = error.timestamp;
    this.contractVersion = error.contract_version;
  }
}

export async function finalCutReviewRequest<T>(
  baseUrl: string,
  path: string,
  init: RequestInit = {},
): Promise<T> {
  const response = await fetch(`${baseUrl}${path}`, {
    ...init,
    headers: {
      "Content-Type": "application/json",
      ...(init.headers ?? {}),
    },
  });
  const body = (await response.json()) as Envelope<T> | ErrorEnvelope;
  if (!response.ok) {
    const error = (body as ErrorEnvelope).error;
    if (error) {
      throw new FinalCutReviewHttpError(error, response.status);
    }
    throw new Error(`HTTP ${response.status}`);
  }
  const envelope = body as Envelope<T>;
  return envelope.data as T;
}

export class FinalCutReviewClient {
  constructor(private readonly baseUrl: string) {}

  request<T>(path: string, init: RequestInit = {}): Promise<T> {
    return finalCutReviewRequest<T>(this.baseUrl, path, init);
  }

  listProjects(init: RequestInit = {}): Promise<ProjectDTO[]> {
    return this.request<ProjectDTO[]>("/api/v1/final-cut-review/projects", init);
  }

  getProject(projectRefId: string, init: RequestInit = {}): Promise<ProjectDTO> {
    return this.request<ProjectDTO>(`/api/v1/final-cut-review/projects/${projectRefId}`, init);
  }

  command<TData, TPayload extends object>(
    path: string,
    envelope: CommandEnvelope<TPayload>,
    init: RequestInit = {},
  ): Promise<TData> {
    return this.request<TData>(path, {
      ...init,
      method: init.method ?? "POST",
      body: JSON.stringify(envelope),
    });
  }
}
